PACKAGECONFIG:append = " kms"
PACKAGECONFIG:append:j721s2 = " opencv zbar"
PACKAGECONFIG:append:mx6-generic-bsp = " opencv zbar"
PACKAGECONFIG:append:mx6ul-generic-bsp = " opencv zbar"
PACKAGECONFIG:append:mx8m-nxp-bsp = " opencv zbar"
PACKAGECONFIG:append:mx93-nxp-bsp = " opencv zbar"
PACKAGECONFIG:append:mx95-nxp-bsp = " opencv zbar"
