EXTRA_OECMAKE:append:mx91-generic-bsp = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
EXTRA_OECMAKE:append:mx93-generic-bsp = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
EXTRA_OECMAKE:append:mx8mm-generic-bsp = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
EXTRA_OECMAKE:append:mx8mn-generic-bsp = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
EXTRA_OECMAKE:append:mx8mp-generic-bsp = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
EXTRA_OECMAKE:append:mx6ul-generic-bsp = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
EXTRA_OECMAKE:append:k3 = " -DCFG_TEE_FS_PARENT_PATH='/mnt/config/optee' "
